tnd_forms:
  provider: formspree
  css:
    form: 'max-w-md pb-5'
    control: ''
    required: ''
    input: block w-full bg-white text-grey-darker border border-grey py-3 px-4 mb-3 leading-tight focus:outline-none
    textarea: block w-full bg-white text-grey-darker border border-grey py-3 px-4 mb-3 leading-tight focus:outline-none h-48
    label: block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2
    select: block appearance-none w-full rounded-none w-full bg-white text-grey-darker border border-grey py-3 px-4 leading-tight focus:outline-none focus:outline-none focus:shadow-outline
    select_wrapper: inline-block relative w-full mb-3
    select_fake: pointer-events-none h-full absolute top-0 right-0 flex items-center px-2 text-grey-darker
    submit: block text-xl text-white bg-gray-800 hover:bg-gradient w-full px-4 py-2 rounded lowercase
tnd_seo:
  jsonld: true
  enable_follow: true
  default_image: images/tnd-social.png
tnd_redirects:
  use_aliases: true
  rules:
  - origin: /fr/*
    target: /fr/404.html
    code: 404
tnd_socials:
  services:
    - name: github
      handle: theNewDynamic
      icon: github
    - name: twitter
      handle: theNewDynamic
    - name: linkedin
      handle: theNewDynamic
    - name: email
      handle: welcome@thenewdynamic.com
tnd_iubenda:
  no_markup: false
  version: 'v1.1'
tnd_headers:
  groups:
    - headers:
      - field: Content-Security-Policy
        value:
          default-src: 
            - self
          style-src:
            - self
            - unsafe-inline
          script-src: 
            - self
            - unsafe-eval
            - https://cdn.usefathom.com 
            - https://identity.netlify.com 
            - https://unpkg.com
          prefetch-src: 
            - https://thenewdynamic.imgix.net
          object-src: 
            - none
          img-src: 
            - self 
            - https://thenewdynamic.imgix.net 
            - https://img3.usefathom.com
          font-src: 
            - self
          base-uri: 
            - none
          connect-src: 
            - self
            - https://cdn.usefathom.com
      - field: Strict-Transport-Security
        value: max-age=15768000
      - field: X-Xss-Protection
        value: 1; mode=block
      - field: X-Frame-Options
        value: DENY
      - field: X-Content-Type-Options
        value: nosniff
      - field: Referrer-Policy
        value: strict-origin-when-cross-origin
      - field: Feature-Policy
        value: camera 'none'; geolocation 'none'; microphone 'none'
addresses:
  - 234 Fifth Ave. • New York, NY • 10001
  - 4267 St Laurent Blvd, Montréal, Québec H2W 1Z4
