image:
  file: .gitpod.Dockerfile

tasks:
   - name: Install Hugo dependencies
     before: brew install hugo
     init: echo "Your version of Hugo is `hugo version`"
     command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0
  - command: 'hugo server --baseUrl $(gp url 1313) --appendPort=false'
  
ports:
  - port: 1313
    onOpen: open-preview
