styles:
- name: main
  path: css/style.css
  use:
  - postcss
  - postprocess
  fingerprint: config/fingerprint-minify()
  minify: config/fingerprint-minify()
# As we cannot use our own names for the files, we use a hardcoded fontface declaration rather
# than using HUGE/Fonts
- name: fonts
  path: fonts/index.css
  internal: true